import Head from 'next/head';
import Image from 'next/image';
import { GetStaticProps, NextPage } from 'next';
import { Character, GetCharacterResults } from '../../types';


const Home: NextPage<{characters: Character[]}> = ({characters}) => {
  return (
    <>
      <Head>
        <title>My First Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {characters.map((character) => {
        return <div key={character.id}>{character.name}
          <Image
            src={character.image}
            alt={character.name}
            width="200"
            height="200"
          />
        </div>
      })}
    </>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {
  const res = await fetch('https://rickandmortyapi.com/api/character');
  const { results }: GetCharacterResults= await res.json();

  console.log(results)

  return {
    props: {
      characters: results || null,
    }
  }
}

export default Home